[versions]
agp = "8.7.2"
firebaseDatabase = "21.0.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.1.4"
googleGmsGoogleServices = "4.4.2"
firebaseFirestore = "25.0.0"
playServicesTasks = "18.2.0"
playServicesTasksVersion = "18.0.2"
securityCrypto = "1.0.0"
volley = "1.2.1"
retrofit = "2.9.0"
ion = "1.9.4"

[libraries]
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabase" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebaseDatabase" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "playServicesTasks" }
play-services-tasks-v1802 = { module = "com.google.android.gms:play-services-tasks", version.ref = "playServicesTasksVersion" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
retrofit = {module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
amazon-ion = { group = "com.amazon.ion", name = "ion-java", version.ref = "ion" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

